kind: pipeline
type: docker
name: gloflow

workspace:
  #IMPORTANT!! - this is where Drone will clone the gloflow repo, and where the gf_builder
  #              container is placing all its code.
  base: /home/gf

steps:

  #-------------------------------
  #TEST
  - name: test
    image: glofloworg/gf_builder
    commands:
      #"-u" - run unbuffered to see all stdout/stderr as it happens
      - python -u /home/gf/build/gf_builder/gf_builder.py -run=test
    when:
      event:
        - push
      branch:
        - master

  #-------------------------------
  #BUILD
  - name: build
    image: glofloworg/gf_builder
    commands:
      #"-u" - run unbuffered to see all stdout/stderr as it happens
      - python -u /home/gf/build/gf_builder/gf_builder.py -run=build
    when:
      event:
        - push
      branch:
        - master

  #-------------------------------
  #BUILD_CONTAINERS
  - name: build_containers
    image: glofloworg/gf_builder
    commands:
      #"-u" - run unbuffered to see all stdout/stderr as it happens
      - python -u /home/gf/build/gf_builder/gf_builder.py -run=build_containers
    when:
      event:
        - push
      branch:
        - master

  #-------------------------------