kind: pipeline
name: gloflow

steps:
  - name: build
    image: glofloworg/gf_builder
    command:
      - python /home/gf/gf_builder.py
    when:
      event:
        - push
      branch:
        - master