kind: pipeline
type: docker
name: gloflow

workspace:
  #IMPORTANT!! - this is where Drone will clone the gloflow repo, and where the gf_builder
  #              container is placing all its code.
  base: /home/gf

steps:
  - name: build
    image: glofloworg/gf_builder
    commands:
      - python /home/gf/build/gf_builder/gf_builder.py
    when:
      event:
        - push
      branch:
        - master