kind: pipeline
type: docker
name: gloflow

steps:
  - name: build
    image: glofloworg/gf_builder
    commands:
      - python /home/gf/gf_builder.py
    when:
      event:
        - push
      branch:
        - master