FROM ubuntu:20.04



RUN mkdir /home/gf

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    curl \
    wget \
    zip

# PY_DEPENDENCIES
RUN pip3 install \
    delegator.py \
    colored \
    beautifulsoup4 \
    requests \
    boto3

# RUST_DEPENDENCIES
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    # libglib2.0-dev \
    libcairo2-dev

#-----------------------------
# RUST
# IMPORTANT!! - "-y" - passing it in at the end is for non-interactive installation, preventing
#                      Rust installer from prompting the user for input (since we're in a container).

RUN curl -sf -L https://static.rust-lang.org/rustup.sh | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo --version

# RUST_NIGHTLY - needed by PyO3 package
RUN rustup self update
RUN rustup toolchain install nightly
RUN rustup run nightly rustc --version
RUN rustup default nightly

#-----------------------------
# PROTOCOL_BUFFERS_COMPILER - "protoc"

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
RUN ls -al
RUN unzip protoc-3.11.4-linux-x86_64.zip
RUN rm protoc-3.11.4-linux-x86_64.zip
RUN protoc --version