FROM golang

RUN mkdir /home/gf
#-----------------------------
# LIBS
# IMPORTANT!! - do a "apt" update every time packages are installed, to avoid cached
#               "apt" data that is stale and may result in cached IP's that break builds.
# GIT - used by ./ops/utils/gf_build_changes.py to determine which apps changed.
# SED - used by gf_builder to inject Git commit hash into Go code.
RUN apt-get update && \
    apt-get install -y \
    git \
    python \
    python-pip \
    nodejs \
    npm \
    docker.io \
    sed \
    curl

RUN pip install \
    delegator.py \
    colored \
    beautifulsoup \
    requests \
    'fabric<2.0'

RUN npm install -g typescript
RUN npm install -g uglify-js

#-----------------------------
# RUST
# IMPORTANT!! - "-y" - passing it in at the end is for non-interactive installation, preventing
#                      Rust installer from prompting the user for input (since we're in a container).
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
#-----------------------------
#ENTRYPOINT ["python", "/home/gf/build/gf_builder/gf_builder.py"]