FROM ubuntu:22.04

RUN echo "1"
RUN mkdir /home/gf

# needed to avoid user prompt durring installation
# of tzdata
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    wget

# used for container building, since gf_builder_go container
# is used for container building as well. if a different container is used
# for container building then remove this.
RUN apt-get install -y docker.io

# libvips-dev - dependency for golang image processing package "bimg"
#               used in gf_images app, for image transformations and pipelines.
RUN apt-get install -y libvips-dev

# ffmpeg - dependency for golang video operations, and needed in tests
#          to be invoked via CLI
RUN apt-get install -y ffmpeg

# PY_DEPENDENCIES
RUN pip3 install \
    delegator.py \
    colored \
    beautifulsoup4 \
    requests \
    boto3

# RUST_DEPENDENCIES
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    # libglib2.0-dev \
    libcairo2-dev
    
#-----------------------------
# GO
RUN wget https://golang.org/dl/go1.19.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz

# has to be added this way to PATH, to work in a Dockerfile
ENV PATH=$PATH:/usr/local/go/bin

RUN go version

#-----------------------------
# ENTRYPOINT ["python3", "-u", "/home/gf/ops/cli__build.py", "-run=build_go"]