FROM alpine:3.12.0

RUN apk update
RUN apk upgrade

RUN adduser --home /home/gf --disabled-password gf
RUN mkdir -p /home/gf/bin
RUN mkdir -p /home/gf/logs
RUN mkdir -p /home/gf/config

RUN chown -R gf /home/gf

RUN apk add --update bash

#------------
ENTRYPOINT ["/home/gf/bin/gf_eth_monitor_worker_inspector"]

#------------
ADD build/gf_eth_monitor_worker_inspector /home/gf/bin/gf_eth_monitor_worker_inspector