FROM ubuntu:22.04

RUN echo "3"
RUN mkdir /home/gf

RUN apt-get update
RUN apt-get install -y \
    curl \
    git

#-----------------------------
# PYTHON
RUN apt-get install -y \
    python3 \
    python3-pip

# PY_DEPENDENCIES
RUN pip3 install \
    delegator.py \
    colored==1.4.4 \
    beautifulsoup4 \
    requests \
    boto3

#-----------------------------
# NODEJS_TOOLS

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
RUN node -v && npm -v

RUN npm install -g typescript
RUN npm install -g uglify-js
RUN npm install -g sass

#-----------------------------

WORKDIR /home/gf