



# PORTS
port:         4050
port_metrics: 9110

# MONGODB
mongodb_host:    "127.0.0.1:27017"
mongodb_db_name: "gf_eth_monitor"

# INFLUXDB
influxdb_host: "127.0.0.1:8086"

# SQS
aws_sqs_queue: "gf_eth_monitor"

# WORKERS_INSPECTORS_HOSTS
workers_inspectors_hosts: "127.0.0.1:2000"

# SENTRY_ENDPOINT
sentry_endpoint: ""