name: gf_p2p_tester_dev
on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/gf_p2p_tester_dev.yaml"
      - 'go/gf_core/**'
      - 'go/gf_extern_services/gf_aws/**'
      - 'go/gf_rpc_lib/**'
      - 'go/gf_p2p/**'

  # workflow is also triggered via github REST API/manually
  workflow_dispatch:

env:
  ENV: dev
  AWS_REGION: us-east-1
  CONTAINER_IMAGE: glofloworg/gf_p2p_tester
  IMAGE_TAG: latest

jobs:

  #--------------------------------------------------------------------
  # BUILD
  build:
    runs-on: ubuntu-latest
    steps:

      #-------------------------------
      # GIT_CHECKOUT
      - uses: actions/checkout@v3

      #-------------------------------
      # GO_BUILD

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      
      - name: install dependencies
        run: |
          go version
          go get -d ./...
      
      - name: add git commit hash
        run: |
          sed -i 's/GF_COMMIT_SHA/${{ github.sha }}/g' go/gf_core/gf_sys_release_info.go
          
      - name: golang build
        run: |
          cd go/gf_p2p/gf_p2p_tester
          go build 

      #-------------------------------
      # CONTAINER_BUILD
      - name: build container
        run: |
          docker build --file go/gf_p2p/gf_p2p_tester/Dockerfile --tag ${{ env.CONTAINER_IMAGE }}:${{ env.IMAGE_TAG }} .
          docker images

      #-------------------------------
      # DOCKER_LOGIN
      - name: login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_GF_P2P_TESTER }}

      #-------------------------------
      # CONTAINER_PUBLISH
      - name: publish container to dockerhub
        run: |
          docker push ${{ env.CONTAINER_IMAGE }}:${{ env.IMAGE_TAG }}

      #-------------------------------
  
  #--------------------------------------------------------------------
  # NOTIFY_COMPLETION
  notify_completion:
    needs: build
    runs-on: ubuntu-latest
    steps:

      #-------------------------------
      # GIT_CHECKOUT
      - uses: actions/checkout@v3
      
      #-------------------------------
      # INITIALIZE_PYTHON3
      - name: initialize python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install python3 dependencies for cli__build.py
        run: |
          pip3 install -r requirements.txt

      #-------------------------------
      # NOTIFY_COMPLETION
      - name: notify completion via HTTP
        env:
          GF_NOTIFY_COMPLETION_URL: ${{ secrets.GF_NOTIFY_COMPLETION_URL__GF_P2P_TESTER }}
        run: |
          python3 ops/cli__build.py -run=notify_completion -app=gf_p2p_tester

      #-------------------------------

  #--------------------------------------------------------------------